# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_of_mailing',
            field=models.DateTimeField(),
        ),
    ]
